
CREATE OR REPLACE PACKAGE ORDER_PROCESSOR AS

    PROCEDURE PROCESS_AND_FETCH(
        P_CUSTOMER_ID  IN NUMBER,
        P_TOTAL_AMOUNT IN NUMBER,
        P_ORDER_CURSOR OUT SYS_REFCURSOR
    );

END ORDER_PROCESSOR;
/